apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: openliberty-samplewebapp
spec:
  applicationImage: quay.io/hamblrt/sample-web-app:1.0
  applicationName: openliberty-samplewebapp
  replicas: 2
