apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: openliberty-samplewebapp
spec:
  applicationImage: openliberty-samplewebapp
  applicationName: openliberty-samplewebapp
  expose: true
  pullPolicy: IfNotPresent
  replicas: 2
  resources: {}
  envFrom:
    - configMapRef:
        name: sample-config
  route:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  service:
    port: 9443
    type: ClusterIP
