apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo
nameSuffix:
  -dev

bases:
  - ../../base

resources:
  - sample-config.yaml

patchesStrategicMerge:
- openlibertyapplication-openliberty-samplewebapp.yaml
